name: Deploy to slides repo

on: push

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    name: copy site folder to slides repo

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Push update file to slides repo
      uses: dmnemec/copy_file_to_another_repo_action@3fe42250d47e0764da9de9939b151b09a26e5857
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'slides/site/.'
        destination_repo: 'Melody12020831/Slides'
        destination_branch: 'main'
        destination_folder: 'docs'
        user_email: 'melody12020831@outlook.com'
        user_name: 'Melody'